security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\PolyGardeUser:
            algorithm: auto



    providers:
        
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_SUPER_ADMIN'
        poly_garde_provider:
            entity:
                class: App\Entity\PolyGardeUser
                property: username
        all_users:
            chain:
                providers: ['in_memory','poly_garde_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: all_users
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
